### PR TITLE
Feature/7 connect users

### LINKED ISSUE #7: Connect the user views to the API

### PR DESCRIPTION
**Pull request by Karvel**
Wire up user service and components to API. User token on user detail page to be addressed shortly. Closes #7.

### CODE REVIEW

**Comment by Karvel** [comment]
Now only shows token of logged in user on user detail page.

**Comment by Karvel** [comment]
Add user form works.

**Comment by Karvel** [comment]
Edit user form now working.

**Comment by Karvel** [comment]
Delete user working.

**Comment by Karvel** [comment]
Now able to change a user's role membership from the user form.

**Comment by Karvel** [comment]
Now handling duplicate email error and displaying to user.

**Comment by nick-herrera** [comment]
- [x] After creating or editing a user, redirect to user to the user list.
  - [x] Display a "save successful" toast message after redirecting.
- [x] Turn off autocomplete on forms
- [x] Use a single column of Roles on the `user-form`
- [x] Display an error message when the user goes to the `user-detail` page for a user that doesn't exist.
- [x] Ditto for `user-form`
- [x] Remove flash of unstyled content (FOUC) when going to the user edit form. (The password field displays briefly.)
- [x] Make the md-whiteframe in the user-form 600px wide
- [x] Make the "delete" button on delete modal blue.
- [x] Make the email address smaller on the user-detail page
- [x] Cancelling the delete modal incorrectly displays an error message

**Comment by Karvel** [comment]
- [x] Expand form inputs to 100% form width

**Comment by Karvel** [comment]
PR updated to address above comments.

**Comment by Karvel** [comment]
- Moved edit and delete buttons and functionality from `user-list` view to `user-detail` view.
- Moved `ui-sref` to row in `user-list` view, added styling on hover.

**Comment by silaslangley98** [comment]
The Edit User button is slightly higher than the Delete User button. See image below. The straight black line helps show that the buttons are not aligned.
screenshot_11

**Comment by silaslangley98** [comment]
There is an error message when trying to delete a user and the user isn't deleted. I'm unsure if this is the expected behavior at this point for some reason. If it's not the expected behavior then it needs to be addressed.

**Comment by silaslangley98** [comment]
On the User view, the full name descenders overlap with the email ascenders. See the highlighted portion of the screenshot below:
screenshot_12

**Comment by silaslangley98** [comment]
Long email addresses cause the Delete and Edit User buttons to drop down. They also cause the bottom of the Delete User button to be cut off. See image below:
screenshot_13

**Comment by silaslangley98** [comment]
For some users, the Edit User and Delete User buttons are stacked and the bottom and the right of the Delete User button is cut off. See image below:
screenshot_14

**Comment by silaslangley98** [comment]
There is no Cancel button on the Create User form. It seems like there should be.

**Comment by Karvel** [comment]
Issues above have been addressed (button height a non-issue, 500 errors on user delete external to this project).

**Pull request merged**
