### PR TITLE
feature/72 persistent browser history

### PR DESCRIPTION
**Pull request by juliancoleman**
- [x] append query to the url
- [x] execute query from url
- [x] refill the `query-builder` form when a query exists in the url

### CODE REVIEW

**Comment by juliancoleman** [comment]
not ready for merge yet. Opening PR to keep track of changes

**Comment by juliancoleman** [comment]
This PR is ready for review @nick-herrera @silaslangley98

**Comment by silaslangley98** [comment]
Query results are not being displayed when executing a query, even when the limit is set to a small number.

**Comment by juliancoleman** [comment]
Ready for testing

**Comment by silaslangley98** [comment]
- A console error is often thrown when executing a query.
- [x] Fix the console error.
- Two console errors are thrown after: (1) Executing a query (2) Then changing the schema to another option in the Schema drop-down menu. 
- [x] Fix the two console errors.
- Clicking the browser's back button doesn't cause the previous query to be retrieved, which was a requirement of Issue #72. Instead, it causes the previous view to display.
- [x] Make it so that clicking the browser's back button causes the previous query to be retrieved.

**Comment by juliancoleman** [comment]
I'm not sure I'll be able to fix the error around `Refused to set unsafe header "content-length"`. Was this the one you're referring to?

**Comment by silaslangley98** [comment]
No. These are the errors I'm getting:

(1) angular.js:13920 TypeError: Cannot read property 'filter' of undefined
    at getSchema (record-browser.component.js:33)
    at record-browser.component.js:26

(2) angular.js:13920 TypeError: vm.schemaList.filter is not a function
    at queryBuilderController.vm.getSchemaDetails (query-builder.component.js:42)

(3) angular.js:13920 Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: schema in queryBuilder.schemaList, Duplicate key: string:i, Duplicate value: i

**Comment by juliancoleman** [comment]
Okay. Thank you for the stack traces

**Comment by nick-herrera** [comment]
@juliancoleman The first error from @silaslangley98's last comment is still not fixed.

To reproduce the issue, go to `/data` choose a schema and execute the query. Notice the error.

Also, the "Add filter" button and ordering is permanently disabled.

**Comment by juliancoleman** [comment]
I am not getting that error at all. Even after changing the schema, and rerunning the execution. Did we want it to be disabled, or do we wanna re-enable it?

**Comment by silaslangley98** [comment]
The error doesn't occur every time. Keep trying and you will get it. I'm trying to isolate consistent reproduce steps, if there are any. No luck so far.

**Comment by juliancoleman** [comment]
I'm having no luck, but I'm greatly considering just starting over my work for this PR. Never been so bothered by this in my life. `vm.schemaList.filter` returns `undefined` even without my additions. If I try to alleviate this issue, I get a ton of `Duplicate md-option values are not allowed in a select. Duplicate value "" found.` errors.

**Pull request closed without merging**
