### PR TITLE
feat(index): create and  use a favicon

### LINKED ISSUE #63: Create and use a favicon

### PR DESCRIPTION
**Pull request by juliancoleman**
this adds the favicon link to `index.html`, and includes this [image](https://mntge.com/static/favicon.png).

closes #63

### CODE REVIEW

**Comment by juliancoleman** [comment]
OOOOHHHHHH MY GOD

**Comment by juliancoleman** [comment]
If I had a dollar...

**Comment by juliancoleman** [comment]
rebasing. hang on

**Comment by irms** [comment]
hehehehe

**Pull request merged**
