### PR TITLE
Feature/8 connect roles

### LINKED ISSUE #8: Connect the role views to the API
Awaiting API implementation

### PR DESCRIPTION
**Pull request by Karvel**
Wire up role and policy service and components to API. To be merged in after #7. Closes #8.

### CODE REVIEW

**Comment by Karvel** [comment]
To be merged after #55 and #66.

**Comment by Karvel** [comment]
- Abstracted role functions into a service.
- Moved `ui-sref` to row in `role-list` and `policy-list` views, added styling on hover.

**Comment by Karvel** [comment]
Merged dev into branch and fixed merge conflicts. Brought relevant #55 changes to respective role and policy endpoints.

**Comment by Karvel** [comment]
- [x] Role/Policy forms - Fix redirect upon successful role or policy creation.
- [x] Role form - edit role (styling) - Adjust alignment of add and close user buttons to match edge of input and submit button.
- [x] Policy form - Add simple error handling on bad request errors (proper solution to be addressed in a separate pull request).
- [x] Role/Policy forms - add required message to textarea.
- [ ] <del>Policy form (styling) - Add margin to bottom of textarea.</del>

**Comment by silaslangley98** [comment]
Regarding the **Policy View**: trying to create or update an empty JSON object or a JSON object with bad input causes the "Saving..." Button to remain disabled and a console error to be thrown. The User should be notified that something is wrong with the JSON input and there should also be some mechanism whereby the Saving... button again becomes the enabled Create or Update button.
- [x] Fix empty JSON resulting in unending "Saving..." button in the Create/Edit Policy form.

**Comment by Karvel** [comment]
Silas' comment above to be addressed fully through #67 and #68.

**Comment by Karvel** [comment]
Above issues addressed; decision reversed on adding margins to textarea.

**Comment by Karvel** [comment]
- [x] Policy form - edit policy - update catch to handle error upon save attempt of badly formatted or absent JSON.

**Comment by Karvel** [comment]
Form data now passed to function with basic error handling for incorrectly formatted JSONs. Form also serves an error to user upon submitting an invalid policy document update.

**Comment by silaslangley98** [comment]
@nick-herrera Passes testing. Ready for code review.

**Pull request merged**
